### ISSUE TITLE
Update to Marketplace Challenge Pools Total

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#314]
3/2 scope decision - list total value of all pTokens funded in this marketplace. use the same preview + expand UX we use to list marketplace blockchains/projects

Update in two places - Marketplaces list, Marketplace / Rewards tab

**Comment by elisemarika** [comment]
this looks resolved now

**Comment by elisemarika** [comment]
Put this on pause, not must have

**Comment by elisemarika** [comment]
@drakedanner @nftchance it's fine that we show pToken value here instead of USD value because we only have one pToken in our allowlist, but at GTM when we have many we either need to 1. support USD value or 2. list total value of all pTokens funded in this marketplace. what do you recommend based on feasibility of calculating current USD value across a number of tokens?

![Image](https://user-images.githubusercontent.com/93347510/221268216-4cc6c729-8db4-4ca4-a635-7cd54c007706.png)

**Comment by elisemarika** [comment]
@nftchance just following up on my question above when you have a chance to review :)

**Comment by nftchance** [comment]
Apologies for missing this, calculating USD value will be rather cumbersome unless using an 3rd party API which could become quite expensive rather quickly.

pToken and respective amounts is perfect!

**Comment by elisemarika** [comment]
3/2 scope decision - list total value of all pTokens funded in this marketplace. use the same preview + expand UX we use to list marketplace blockchains/projects
