### ISSUE TITLE
[public report]: Remove Challenge Start Date

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#332]
### User Impacted

0xc6Ac8FC10242771eA79B1Bdbb4d72f775AF9587F

### Discord ID (including number)

danner.eth

### Workflow Impacted

Brainstorm

### Feature Impacted

Create Marketplace

### Issue description

![image](https://user-images.githubusercontent.com/11461756/217640958-34247e99-83c8-4d01-bd58-5a14b77eb5ac.png)

when choosing dates in the future for submission and review, the app gives me dates in the past

https://beta.metricsdao.xyz/app/brainstorm/m/0xcd7dcdd46bd309368af8dbf085cb53f534d07a54/sr/1/timeline

### Blocking

yes it is

**Comment by drakedanner** [comment]
It appears that the "Start Date" input is being used to indicate when Signal Deadline is and that it is working off of UTC instead of a local timestamp.

When creating a challenge that starts accepting submissions "now", it puts the claim to submit deadlines 5 hours in the past

I believe the claim to submit deadline is supposed to be 75% of the way through the submission period.

**Comment by drakedanner** [comment]
![image](https://user-images.githubusercontent.com/11461756/217642265-7cb75a6e-f999-435a-9837-4e48929d4f88.png)
Believe the highlighted text should show a dynamic date based on my start and end dates

**Comment by sebruiz** [comment]
how we were doing date calculations was off. This might be fixed now.

**Comment by elisemarika** [comment]
team decision 2/13 - removing submissions start due to not wanting to fake it in the app or support this level of granularity on chain. Instead, submissions will only have a deadline

When must submissions be entered by?
Select a date and time (in your local time zone) to schedule the submit deadline. Submissions open and are accepted as soon as the Challenge is launched.

Challenge / Timeline & Deadlines --> Submissions open = always when the challenge became active

**Comment by drakedanner** [comment]
I'm renaming this ticket to be clearer

**Comment by drakedanner** [comment]
Can we merge this PR? 

https://github.com/MetricsDAO/xyz/pull/438
