### ISSUE TITLE
Users don't know if they meet pre-requisites

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#396]
A user asked to have a badge minted to them so that they could participate as a Reviewer. It turns out they already have this badge. 
![image](https://user-images.githubusercontent.com/11461756/218883035-9966cad7-772e-44d5-a4e1-89b9ae668597.png)

I wonder if it is possible to show a user whether or not they meet the pre-requisites 
![image](https://user-images.githubusercontent.com/11461756/218883096-46614911-6df4-4c78-8fc0-f8fb294e6fee.png)

**Comment by elisemarika** [comment]
@sebruiz @thehannahlerman this issue relates to this one: https://github.com/orgs/MetricsDAO/projects/5/views/6?pane=issue&itemId=20379593

instead of hiding any buttons, we could disable the button and provide some sort of messaging on why they can't click/take that action. imagine I hover on the disabled claim the review button and it displays the message "You must hold this badge to review and score submissions: Marketplace Factory 0xA87...ebeA #3 

perhaps we could also show a validation in the Marketplace / Prerequisites and Challenge / Prerequisites per user to display yes you qualify or no you don't. imagine a green checkmark vs. red x or something

@A4x1 @mahgillis what do you think?

**Comment by drakedanner** [comment]
X or check icons on the ore-requisites tab may be nice too

As a user that knows pre-requisites are required, I navigate to the pre-requisites tab to see if i am able to participate

BUT 

I do not know if I hold these tokens or how many of them I may hold

**Comment by A4x1** [comment]
I agree with Elise. Disabling the button and providing a message. I also like the idea that users can directly see what challenges they are immediatly qualified for.

**Comment by nftchance** [comment]
To bring clarity to the conversation here, there are two distinct needs.

1. Being able to run a transaction.
2. Having a transaction that is prepared to run.

To support the first, a `balanceOf(tokenId)` would be needed to filter a full list (whether using live-filtered events or an indexer-cached result (presumably a balance multi-call)) against in order to determine which a user **will have access to when they have built a valid transaction.**

To support the second, the active error of the transaction should be utilized.

**Comment by elisemarika** [comment]
ensuring we see @mahgillis proposed UX which was on this similar but more narrow issue cc @A4x1 @drakedanner @nftchance @sebruiz https://github.com/MetricsDAO/xyz/issues/384#issuecomment-1439034630

[https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=5445%3A38986&t=LfsLueRKCZaMmDo6-1](https://github.com/orgs/MetricsDAO/projects/5/views/url)

**Comment by drakedanner** [comment]
https://github.com/nftchance/charlie/blob/master/frontend/src/utils/getBalances.tsx

@nftchance notes that we can essentially use this code but adjust the targets

**Comment by mahgillis** [comment]
Good idea @sebruiz, I'll update designs. I originally had a red x but second guessed myself thinking it might be too aggressive.
