### ISSUE TITLE
"I'm able to" permission filters on Marketplace/Challenge pages

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/xyz#413]

**Comment by elisemarika** [comment]
@gnomadic is this the "I'm able to" filter on Marketplaces or something else?

![Image](https://user-images.githubusercontent.com/93347510/219428831-445fef5b-29ec-4cc0-93cf-cfab61e138e4.png)

**Comment by gnomadic** [comment]
this is from the spreadsheet but I'm under the impression it's a "filter on what I can do"

**Comment by sebruiz** [comment]
Want to call out that this is a hard problem. This requires a user to send us all the badges (ERC-1155) they own so that we can compare on the server as to which marketplace/challenges they qualify for. That requires a query to a data provider like https://moralis.io/

**Comment by sebruiz** [comment]
Protocol and app team met and think we can do this in a 2-phase approach to avoid premature optimization.

Phase 1: Increase the page size on the relevant list views so that we can do a client-side multicall.

Phase 2: Scaling issues arise and need to limit page-size and utilize pagination. Now we can introduce Moralis and do it the "right way".
