### ISSUE TITLE
Network discoverability and integrations between Metrics App and Badger

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#639]

**Comment by elisemarika** [comment]
Ideas

- Search/discover/create within launch a challenge flow
- Embed Networks page from Badger in Metrics App dedicated view
- When creating a new network we need to add Managers so the protocol can auto-slash << onboard network to Metrics App >> deploy Manager module and make Metrics protocol a Manager
- See Network stats in the Metrics App << how active, what are they doing, "ecosystem" style info
- My Networks view within Profile << Networks then drilldown to Badges

**Comment by drakedanner** [comment]
Expanding on above:

**In Context**

- Search/discover/create within launch a challenge flow

Marketplace Managers may or may not know which networks they want to enable as Sponsors, Analysts, Reviewers. 

If they know, then they should be able to search for a specific network.

If they don't know, then they should be able to explore options and be served relevant networks.

**Discovery**

- Embed Networks page from Badger in Metrics App dedicated view
- See Network stats in the Metrics App << how active, what are they doing, "ecosystem" style info

While the Badge discovery views get us started, proper discovery of networks within the Metrics context will include aggregate stats about the actors in that network. ie: 

| Network        | Members | Commitments | Great Outcomes | Satisfaction Rate | Total Winnings |
|----------------|---------|-------------|----------------|-------------------|----------------|
| Expert IBC     | 3       | 2           | 1              | 50%               | $2,500         |
| Crypto Curious | 5,000   | 1,933       | 1,894          | 98%               | $12,000        |
| Expert EVM     | 14      | 12          | 11             | 92%               | $12,0000       |
| Pine Analytics | 29      | 14          | 14             | 100%              | $15,000        |

After talking with @nftchance about this a bit earlier today, I'm rolling back my thoughts on deploying onchain modules for these networks and making them managers.

Rather than having a permissioned manager that can burn account bound tokens, we can limit the "locking"/"slashing" action to transferable Badges only.

This opens a design space with n-badge wherein a user may be required to have a non-transferrable token representing some access and a transferable token that is locked as a commitment.

**Comment by drakedanner** [comment]
After initial Discovery, we have decided to pause efforts on integrations into the app.

Network Discoverability will be solved for MetricsDAO via Gitbook.

Network Stats will be solved with queries.

Network Discoverability will exist on Badger, in the context of Badger.

**Comment by drakedanner** [comment]
@elisemarika given that we're not taking action in Metrics app on this now, should this be closed?

One item that would improve UX for the operators would be the ability to select from a dropdown when defining the Marketplace (rather than copy / pasting an address) but, we'd want to retain the ability to paste it and this could be addressed later in a separate ticket

**Comment by elisemarika** [comment]
@drakedanner feel free to close and we can open separate tickets in the future yes
